# Generated by Django 2.0.4 on 2018-05-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glavnaya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='FotoUrl',
            field=models.CharField(default='/static/', max_length=300),
        ),
    ]
