# Generated by Django 2.0.4 on 2018-05-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glavnaya', '0002_news_fotourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='published_date',
        ),
    ]
