# Generated by Django 2.0.4 on 2018-05-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glavnaya', '0004_auto_20180502_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='FotoUrl',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.TextField(max_length=70),
        ),
    ]
