# Generated by Django 2.0.4 on 2018-05-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glavnaya', '0005_auto_20180503_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
