# Generated by Django 2.0.4 on 2018-05-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glavnaya', '0007_auto_20180503_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
