# Generated by Django 2.0.4 on 2018-05-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glavnaya', '0009_auto_20180503_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='place',
            field=models.TextField(default=' '),
        ),
    ]
