# Generated by Django 2.0.4 on 2018-05-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glavnaya', '0010_team_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('Тренер', 'Тренер'), ('Сотрудник', 'Сотрудник')], default='Тренер', max_length=15),
        ),
    ]
