# Generated by Django 2.0.4 on 2018-05-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glavnaya', '0012_auto_20180503_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Онлайн', 'Онлайн'), ('Очный', 'Очный')], default='Очный', max_length=10)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
